### ISSUE TITLE
Endpoint to query a summary of Field Visit Reading parameters

### ISSUE THREAD

**Issue by mattfung** [AquaticInformatics/aquarius-sdk-net#143]
Hello, 

I'm wondering if there is a way of querying a summary of field visit reading parameters given a locationIdentifier using the SDK? I notice that there is a `discretereadings` endpoint that provides this information, but I'm not able to find a SDK function that calls this endpoint.

Thanks

**Comment by DougSchmidt-AI** [comment]
Sorry for the slow response @mattfung. The notification from GitHub was buried in a flood of other GitHub notification emails.

The `GET /AQUARIUS/apps/v1/datasets/discretereadings` endpoint is not part of the public API surface:

- `/AQUARIUS/Publish/v2`
- `/AQUARIUS/Acquisition/v2`
- `/AQUARIUS/Provisioning/v1`

The SDK only supports the public API surface, since the private APIs are intended for consumption by our bundled browser apps (Springboard, Data Review Tool, Rating Review Tool, etc). The private APIs can and do change from release to release. So if you build an integration based on a private API and it breaks in a future release, then you're on your own to update it.

But the team works hard to alwyas keep the public API surface backwards compatible. So your integrations based on the SDK will keep working from release to release.

The public API you should consume to get the field visit readings by location is `GET /AQUARIUS/Publish/v2/GetFieldVisitReadingsByLocation`.

Browse to `https://{yourAppServer}/AQUARIUS/apps/v1/swagger-ui/#!/datasets/GetDiscreteReadingDatasetsByLocationIdsdiscretereadings_Get` to see an example.

![image](https://user-images.githubusercontent.com/54773/126229298-bcba0164-1c72-48ec-87ec-9a894fbd35b6.png)

The associated SDK DTO to use is `GetFieldVisitReadingsByLocationServiceRequest`, like this:

```C#
private void FetchAllReadings(IAquariusClient client, string locationIdentifier)
{
    var readings = client.Publish.Get(new GetFieldVisitReadingsByLocationServiceRequest
        {
            LocationIdentifier = locationIdentifier
        })
        .FieldVisitReadings;
    
    // Do stuff with the readings
}
```
